#ifndef CONFIG_H
#define CONFIG_H

#define RENDERER_WIDTH 512
#define RENDERER_HEIGHT 288
#define RENDERER_OFFSCREEN 1.4f
#define LIGHT_STEP 1.0f
#define LIGHT_QUALITY 1.0f
#define WINDOW_WIDTH (RENDERER_WIDTH * 2)
#define WINDOW_HEIGHT (RENDERER_HEIGHT * 2)
#define MODEL_SIZE 16
#define MODEL_MAX_HEIGHT 32
#define DATABASE_PATH "2.5d_lighting.sqlite3"
#define MOUSE_BIAS 0.01f
#define SPEED 500.0f

#endif